### ISSUE TITLE
getting invalid signature but same code worked before

### ISSUE THREAD

**Issue by sultan113054** [Nexmo/verify-android-sdk#22]
Hi 
I am getting the following error when try to run the app but before it works fine.

![capture](https://cloud.githubusercontent.com/assets/19679715/25562395/e060884c-2da6-11e7-86d1-1170bcaeadd1.PNG)

**Comment by emmaChristine** [comment]
Hi,
Can you please give us the following details so we can investigate this further:
- the sdk version you're using
- in order to check the logs we would also need your app credentials, but please post them privately on our support page https://help.nexmo.com/hc/en-us/requests/new?ticket_form_id=46156 or just by dropping an email to support@nexmo.com

Cheers,
Emma

**Comment by Bajranghudda** [comment]
Hello @emmaChristine, 

I am also facing same problem, a month ago it was working and when I checked now, it's not.
 
I am using it as a module dependency and it's version in gradle file is - 
      **versionCode 6
      versionName "4.0.0"**

And which credentials you are talking about ? The one which I used to login?

**Comment by archanapareta** [comment]
I was also facing same problem some time ago but still no solution.

**Comment by emmaChristine** [comment]
Dear valued customer. We have made the decision to shutdown our SDK for the Verify product. We have created an implementation guide for our Verify API for iOS and Android: https://www.nexmo.com/blog/2018/05/10/nexmo-verify-api-implementation-guide-dr/. We strongly recommend that you migrate to the API as the SDK will shutdown on the 14th November 2018. Our documentation is in the process of being updated. 

Thank you for using Nexmo.

The Nexmo Team

**Comment by Bajranghudda** [comment]
Thanks @emmaChristine for your response.

But I have one confusion that why app is still working in IOS and not in Android?  Or you shutdown it only for Android as of now and planning to shutdown in IOS too soon? 

Actually my Project manager is asking me so and I don't have any reply for this, Please suggest me any reply so that I can reply him satisfyingly. 

Thanks.

**Comment by TheChrisVela** [comment]
Hi @Bajranghudda the SDKs for Android, iOS, and JavaScript will all be shutdown on 14th November 2018.

**Comment by TheChrisVela** [comment]
Since the SDKs will be shutting down in November, the team will not be able to support any bug reports or feature requests before the shut down occurs.
