### ISSUE TITLE
Verify the verification on the server side

### ISSUE THREAD

**Issue by SteveYurka** [Nexmo/verify-android-sdk#6]
We're currently using Nexmo's java API, and are thinking of integrating client SDK's instead, as they handle the round-robin, number permissions and have extra state listeners, and overall would be a better UX for both end users and developers.

However, it does not seem like it is possible to verify that the client was truly verified on the server side, which can lead to many security flaws. Please correct me if I am wrong here.

Lets use an example where the server must verify that the client owns the phone number, before distributing them a security token / authorizing certain actions. In this scenario the client would be basically sending the server a message saying "Hey I was just verified client side, just trust that fact and give me privileges associated with this phone number / userID". This URL would be easily discoverable and can lead to unauthorized users scraping the database through the server API... it is actually not really feasible to have such a URL to begin with, as it grants privileges based on a process which it cannot internally verify itself

It is therefore not really feasible to store any result / state in relation to the user being verified, such as this userID owns this phone number, as it is again just sent to the server in a message where the server is not able to verify its integrity

However, maybe your intention here is to not communicate with the backend/server at all, and instead provide verification as a stand alone piece, where the client will then use something like the mobile AWS SDK's to do all database/service interaction

On a general note it seems like you guys are a bit fragmented from a product roadmap point of view, I've noticed many other nexmo users have had the same thoughts / had to solve the same issues as myself
1) The server SDK's (or API), should also follow the same process, where the round-robin is (optionally) abstracted away from developers, as well as the phone number setup/permissions/choice being (optionally) abstracted away as well, so that it is truly just a simple 'SMS this number, with this message' type API.

I personally know of many other people who have also recommended a round-robin on different services (eg twilio), to ensure this happens, which ultimately leads to less usage of nexmo (as you guys seem like the best choice), and is of course a waste of developer time

2) The client SDK, especially since it states that your server holds a verified state for 30 days after verification, should also return some type of token on success. We should then be able to pass the users phone number, along with the returned nexmo token, to our own backend, which is then able to call your API to check that the phone number + token actually match a real verification on your side (adding a server verification check onto the client verification)

From what I have seen your competitors don't do these either, but it would really help ensure you guys stay ahead

**Comment by thepeachbeetle** [comment]
Hi Steve, 
Id like to address some of the points/questions you raised here..

I fear you may have mis-understood the security model of the SDK and the service. The security flaws you suggest in fact are not valid.

The first point, you suggest that the client sends a message to the server saying 'i just verified client side'. This is not true, in fact, it is not possible. The client is simply relaying end-user input to the service in relation to an attempt to validate their identity. The client has no knowledge of the correctness or not of that input and has no basis upon which to say 'I am verified now, trust me'. There is also no facility in the API to allow a client to do that. Your are correct that such an API URL could be easily compromised in the manner you describe.

API calls may not be 'discovered and replayed' There are a number of measures to protect against this.
Firstly, all requests are signed using a signature seeded with a timestamp and shared secret known only to the client and the server and not communicated as part of the request. Requests are also authenticated using short-lived authentication tokens which themselves require a securely signed request from the client to generate. There are also numerous velocity rules in place on the service, the details of which are obviously not public.

With this in mind,  your point (2) above, the generation and return of such tokens would add nothing to the existing security model and would simply create a need, client-side to persist this token. (which would itself, open up potential opportunities to exploit that token. The client in this model is entirely stateless and need only pass information that is readily and immediately available to it in order to interact with the service and determine the state of the end user.

I hope this answers your concerns and gives you a better understanding of some of the security features inherent in this service and its associated client SDK.

**Comment by SteveYurka** [comment]
Thanks for your response 

I was talking about developer created backends though, I am sure the way you guys talk to your own server is secure, as you mentioned above

Is there anyway for our own backend to validate that the client who has verified using your SDK is in fact verified?

The situation I am talking about is where we use this SDK to create an account or login from the client, who then sends our own developer backend a session create/login command

Can we verify that on our developer backend?

**Comment by emps** [comment]
hii i have same issue is there any solution ?
im using java / objc sdk to verify the mobile is real number but cant find a way to verify from my backend that it is talking with a real verified client, isnt there a way to recheck with nexmo api same number with a pin code from the server side as well ? to ensure that the mobile is real and not hacker ?

**Comment by ec19846** [comment]
Please contact Nexmo support and we can help you setup a server side validation of the verification status.

**Comment by emps** [comment]
ok thanks

**Comment by fuxpavel** [comment]
I have exactly the same issue

**Comment by emps** [comment]
@fuxpavel im tring contact them, as i get the answer i will post it here, we need api access to recheck pin code with a number from the serverside

**Comment by orlando** [comment]
Any update about this?, we are in the same boat. The idea is to:
1. Verify phone number using the SDK
2. Do a **Verify Search** in the backend to get the phone number and update it in the database (For this we need a `request_id` to use it with the Verify API, or somehow pass the phone number and the parameters as we do in the SDK)

**Comment by orlando** [comment]
@emps did you get an answer from Nexmo about this?

**Comment by emps** [comment]
no they didnt answer my phone call neither email

**Comment by emps** [comment]
0% support from this guys

**Comment by orlando** [comment]
Got an answer from their support, I'll be implementing their suggestions tomorrow. If everything goes good I'll post the implementation here

**Comment by zackd** [comment]
@orlando this is exactly the workflow we have pencilled in

> 1. Verify phone number using the SDK
> 2. Do a Verify Search in the backend to get the phone number and update it in the database (For this we need a request_id to use it with the Verify API, or somehow pass the phone number and the parameters as we do in the SDK)

did you have any success with getting this working ?

**Comment by orlando** [comment]
@zackd yeah, we implemented a part of the android sdk in go. We actually mimic the android implementation https://github.com/hashlabs/nexmo-verify-go-sdk, since go is not a supported language (they support javascript, ios and android)

So we use the android sdk to verify the user, and then we use the repo above to verify it, sending the request as if we were the same user. For this, Nexmo uses the device_id + the app_id, but you can change the scope when you create the application in Nexmo.

So yeah, this is pretty much the only way to do it right now, since there's no way to do cross checking between the SDK and the REST API

**Comment by zackd** [comment]
@orlando thanks, thats really useful info. much appreciated :)

**Comment by zackd** [comment]
NB. it is possible to search by phoneNumber here: https://dashboard.nexmo.com/verify 
but not via the api

**Comment by lornajane** [comment]
A late response to say that we're no longer using the Verify SDK products and instead are encouraging people to integrate with our APIs. There's more information here if you need it: https://www.nexmo.com/blog/2018/05/10/nexmo-verify-api-implementation-guide-dr/
