### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Lcom/google/gson/JsonSerializer;

### ISSUE THREAD

**Issue by xoco70** [Nexmo/verify-android-sdk#8]
I'm so close to choose your solution, but I have a UNEXPECTED TOP-LEVEL EXCEPTION:
I get an error with Gson Library. 
com.android.dex.DexException: Multiple dex files define Lcom/google/gson/JsonSerializer;
How should I do?

**Comment by parthawasthi** [comment]
Hi xoco70,

Thanks for bringing this to our attention. I apologise for the bug and the inconvenience it may have caused you. We've identified the root cause of this as a conflict in the dependencies and we are working to patch it ASAP. We thank you immensely for choosing our Verify SDK—your feedback is invaluable to make the Public Beta better. We'll update you shortly.

Thanks for your patience!

**Comment by emmaChristine** [comment]
Hi xoco70,
Thank you for poiting this out, we have done a quick fix on the library, please pull the repo and get the new verify-beta0.5.aar and make sure you use the same gson library, which is in fact the latest one:
compile 'com.google.code.gson:gson:2.3.1'  , to avoid having to exclude certain groups from compilation.
We have fixed our internal dependency which was due to temporary using local dependencies instead of the ones from maven central repo. All the dependency logic shall be settled when we soon push verify library to maven as well.
In the meantime, please let us know if this was sufficient to enable you to resume your work.

Kind regards,
Emma

**Comment by sjw903** [comment]
app/build.gradle
modify dependencies
provided fileTree(dir: 'libs', include: ['*.jar'])
modify others module /buidl.gradle the same like above

**Comment by emmaChristine** [comment]
Newest verify SDK version 'com.nexmo:verify:4.0.0' is now available on Maven central.
The initial issue you encountered with the beta SDK is probably long time solved, but please do ping us if that's not the case.

Kind regards,
Emma
